# Generated by Django 3.0.7 on 2020-10-17 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import titles.models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_titles_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name'], 'verbose_name': 'Жанр'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name'], 'verbose_name': 'Название произведения'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titles.Categories', verbose_name='Категория произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1450), titles.models.max_value_current_year], verbose_name='Дата публикации произведения'),
        ),
    ]
