# Generated by Django 2.2.9 on 2020-10-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_titles_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name']},
        ),
    ]
