# Generated by Django 2.2.9 on 2020-10-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20201014_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, to='titles.Genres', verbose_name='Жанр'),
        ),
    ]
