# Generated by Django 2.2.9 on 2020-10-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20201018_1436'),
        ('titles', '0005_auto_20201017_2050'),
    ]

    operations = [
    ]
